export const ADAPTERS_VERSION = '0.1.0';
export * from './edo/types.js';
export * from './edo/mockEdoAdapter.js';
export * from './storage/index.js';
export * from './bank/index.js';
export * from './telegram/index.js';
export * from './migration/index.js';
export * from './pos/index.js';
export * from './onec/clientBankExchange.js';
export * from './reports/monthEndPack.js';
export * from './ksp/index.js';
export * from './property/floorplan.js';
export * from './workbot/index.js';
